#!/bin/sh
# Prepares everything the other containers expect to find already in place:
# the CA bundle, the Prosody plugins and their configuration, and the coturn
# configuration. Runs to completion before any other service starts.

set -eu

SCRIPT_NAME=init
. /conf/scripts/lib.sh

CERTS_DIR=/conf/certs
PLUGINS_DIR=/conf/prosody/plugins
PLUGIN_CONF_DIR=/conf/prosody/plugin-conf
PROSODY_CONF_D=/data/prosody/config/conf.d
CA_BUNDLE="$CERTS_DIR/ca-bundle.crt"
SYSTEM_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt


# -----------------------------------------------------------------------------
# Data directories
# -----------------------------------------------------------------------------

create_data_directories() {
    for dir in web transcripts prosody/config/conf.d jicofo jvb; do
        mkdir -p "/data/$dir"
    done
    mkdir -p "$CERTS_DIR" "$PLUGINS_DIR"
}


# -----------------------------------------------------------------------------
# Certificate authorities
# -----------------------------------------------------------------------------
# Containers that talk to customer-operated endpoints need to trust the CA that
# signed them. Producing one bundle here keeps every container independent of
# the base image's certificate tooling.

build_ca_bundle() {
    if [ -r "$SYSTEM_CA_BUNDLE" ]; then
        cp "$SYSTEM_CA_BUNDLE" "$CA_BUNDLE"
    else
        warn "no system CA bundle found; the bundle will contain only EXTRA_CA_FILE"
        : > "$CA_BUNDLE"
    fi

    [ -n "${EXTRA_CA_FILE:-}" ] || return 0

    if [ ! -r "$EXTRA_CA_FILE" ]; then
        die "EXTRA_CA_FILE is set but not readable: $EXTRA_CA_FILE"
    fi

    cat "$EXTRA_CA_FILE" >> "$CA_BUNDLE"
    log "added $EXTRA_CA_FILE to the CA bundle"

    # Trust it here too, so plugin downloads from an internal host work.
    cat "$EXTRA_CA_FILE" >> "$SYSTEM_CA_BUNDLE"
}


# -----------------------------------------------------------------------------
# Prosody plugins
# -----------------------------------------------------------------------------
# A failed download must not take the stack down: the previously downloaded
# copy stays in place and Prosody starts with it.

download_plugins() {
    [ -n "${PROSODY_PLUGINS:-}" ] || { log "no plugins requested"; return 0; }

    split_list "$PROSODY_PLUGINS" | while read -r url; do
        download_plugin "$url"
    done
}

download_plugin() {
    url=$1
    name=$(basename "$url")
    target="$PLUGINS_DIR/$name"
    staging="$target.downloading"

    if wget -q -O "$staging" "$url"; then
        mv "$staging" "$target"
        log "downloaded $name"
        return 0
    fi

    rm -f "$staging"
    if [ -f "$target" ]; then
        warn "could not download $name; keeping the copy already on disk"
    else
        warn "could not download $name and no copy is available"
    fi
}


# -----------------------------------------------------------------------------
# Prosody configuration fragments
# -----------------------------------------------------------------------------
# These are *additional* files dropped next to the configuration the Prosody
# image generates, never on top of it, so the deployment keeps working across
# Jitsi releases. Prosody merges repeated Component declarations key by key, so
# setting a key the generated file does not set is safe.
#
# Prosody expands the conf.d glob with lfs.dir, which does not sort, so load
# order is undefined. Nothing here may depend on it: each fragment sets only
# keys no other file sets. The names carry no numeric prefix, so as not to
# suggest an ordering that does not exist.

render_prosody_fragments() {
    rm -f "$PROSODY_CONF_D"/stack-*.cfg.lua

    render_notification_fragment
    render_moderation_fragment
    render_extra_ca_fragment
}

# Without this, a participant arriving with no token is silently promoted to
# moderator on an empty room.
render_moderation_fragment() {
    is_enabled "${REQUIRE_TOKEN_FOR_MODERATION:-0}" || return 0

    cat > "$PROSODY_CONF_D/stack-moderation.cfg.lua" <<EOF
-- Generated by the stack from REQUIRE_TOKEN_FOR_MODERATION.
Component "${XMPP_MUC_DOMAIN}" "muc"
    token_verification_require_token_for_moderation = true
EOF
    log "moderation requires a token"
}

# Optional. With no endpoint there is nothing to configure, and the plugin
# logs that notifications are off rather than failing.
render_notification_fragment() {
    [ -n "${NOTIFICATION_URL:-}" ] || { log "room notifications disabled"; return 0; }

    # The numeric options land in Lua unquoted, so an empty value would render
    # as `= ` and take Prosody down. Defaulting them keeps a half-filled
    # environment from producing a broken configuration file.
    NOTIFICATION_USERAGENT=${NOTIFICATION_USERAGENT:-Jitsi-Prosody}
    NOTIFICATION_TIMEOUT=${NOTIFICATION_TIMEOUT:-10}
    NOTIFICATION_RETRY_COUNT=${NOTIFICATION_RETRY_COUNT:-5}
    NOTIFICATION_RETRY_DELAY=${NOTIFICATION_RETRY_DELAY:-1}
    export NOTIFICATION_USERAGENT NOTIFICATION_TIMEOUT \
           NOTIFICATION_RETRY_COUNT NOTIFICATION_RETRY_DELAY

    render "$PLUGIN_CONF_DIR/notification.cfg.lua.template" \
           "$PROSODY_CONF_D/stack-notification.cfg.lua" \
           XMPP_MUC_DOMAIN \
           NOTIFICATION_URL NOTIFICATION_USER NOTIFICATION_PASSWORD \
           NOTIFICATION_USERAGENT NOTIFICATION_TIMEOUT \
           NOTIFICATION_RETRY_COUNT NOTIFICATION_RETRY_DELAY

    log "room notifications enabled"
}

render_extra_ca_fragment() {
    [ -n "${EXTRA_CA_FILE:-}" ] || return 0

    cat > "$PROSODY_CONF_D/stack-ca.cfg.lua" <<EOF
-- Generated by the stack. Points Prosody's outgoing TLS at the merged bundle
-- so plugins can reach endpoints signed by a private CA.
ssl = {
    cafile = "/conf/certs/ca-bundle.crt";
}
EOF
}


# -----------------------------------------------------------------------------
# coturn
# -----------------------------------------------------------------------------

render_coturn_config() {
    if [ -z "${TURN_CREDENTIALS:-}" ]; then
        log "TURN_CREDENTIALS is empty; coturn will refuse connections"
    fi

    TURN_EXTERNAL_IP=${TURN_EXTERNAL_IP:-${JVB_ADVERTISE_IPS:-}}
    TURN_EXTERNAL_IP_LINE=""
    [ -n "$TURN_EXTERNAL_IP" ] && TURN_EXTERNAL_IP_LINE="external-ip=$TURN_EXTERNAL_IP"
    export TURN_EXTERNAL_IP_LINE

    # The peer allow-list has to name the stack's own subnet exactly, which is
    # why the compose file pins it instead of letting Docker choose.
    TURN_ALLOWED_PEER_RANGE=${TURN_ALLOWED_PEER_RANGE:-$(subnet_to_range "${STACK_SUBNET:?STACK_SUBNET is required}")}
    export TURN_ALLOWED_PEER_RANGE

    render /conf/coturn/turnserver.conf.template /runtime/turnserver.conf \
           TURN_CREDENTIALS TURN_HOST TURN_EXTERNAL_IP_LINE \
           TURN_RELAY_MIN_PORT TURN_RELAY_MAX_PORT \
           TURN_ALLOWED_PEER_RANGE \
           TLS_CERT_FILE TLS_KEY_FILE
}


# -----------------------------------------------------------------------------

main() {
    create_data_directories
    build_ca_bundle
    download_plugins
    render_prosody_fragments
    render_coturn_config
    log "ready"
}

main "$@"
